# Essa action permite rodar um comando arbitrário (normalmente um 'nix run
# .#alguma-coisa') e commita as mudanças feitas. Ela utiliza o gelos bot para
# fazer os commits.
#
# Alguns exemplos de uso incluem:
# - Arrumar algo que uma contribuição pode quebrar (um vendor hash, por exemplo)
# - Atualizar flake.lock periodicamente

on:
  workflow_call:
    inputs:
      commit-message:
        required: true
        type: string
      command:
        required: true
        type: string
jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
    - uses: tibdex/github-app-token@v1
      id: generate-token
      with:
        app_id: 251209
        private_key: ${{ secrets.GELOS_BOT_KEY }}
    - name: git config
      run: |
        git config --global user.name "gelos-bot"
        git config --global user.email "gelos-bot[bot]@users.noreply.github.com"
    - uses: actions/checkout@v3
      with:
        token: ${{ steps.generate-token.outputs.token }}
    - uses: determinatesystems/nix-installer-action@v4
    - uses: determinatesystems/magic-nix-cache-action@v2
    - run: ${{ inputs.command }}
    - name: git commit
      run: |
        git commit . -m "${{ inputs.commit-message }}" && git push || echo "Nothing to commit"
